self.update_label(self.weather_labels[0], f"Today's Weather as of {current_weather['last_updated']}")
        # self.update_icon_label(self.weather_labels[1], f"http:{current_weather['condition']['icon']}")
        # self.update_label(self.weather_labels[2], f"Current Condition: {current_weather['condition']['text']}")
        # self.update_label(self.weather_labels[3], f"Current Temperature: {current_weather['temp_f']}°F | {current_weather['temp_c']}°C")
        # self.update_label(self.weather_labels[4], f"Current Wind: {current_weather['wind_mph']}mph | {current_weather['wind_kph']}kph {current_weather['wind_dir']}")
        # self.update_label(self.weather_labels[5], f"Current Humidity: {current_weather['humidity']}%")
        # self.update_label(self.weather_labels[6], f"")
        # self.update_icon_label(self.weather_labels[7], f"http:{forecast_weather['condition']['icon']}")
        # self.update_label(self.weather_labels[8], f"Forecasted Condition: {forecast_weather['condition']['text']}")
        # self.update_label(self.weather_labels[9], f"Max Temperature: {forecast_weather['maxtemp_f']}°F | {forecast_weather['maxtemp_c']}°C")
        # self.update_label(self.weather_labels[10], f"Min Temperature: {forecast_weather['mintemp_f']}°F | {forecast_weather['mintemp_c']}°C")
        # self.update_label(self.weather_labels[11], f"Max Wind: {forecast_weather['maxwind_mph']}mph | {forecast_weather['maxwind_kph']}kph")
        # self.update_label(self.weather_labels[12], f"Average Humidity: {forecast_weather['avghumidity']}%")
        # self.update_label(self.weather_labels[13], f"Chance of Rain: {forecast_weather['daily_chance_of_rain']}%")
        # self.update_label(self.weather_labels[14], f"Total Precipitation: {forecast_weather['totalprecip_in']}in | {forecast_weather['totalprecip_mm']}mm")
